/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.8/samples
 */
plugins {
    id("java");
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17);
    }
}

tasks.withType<JavaCompile> {
    var compilerArgs = options.compilerArgs;
    compilerArgs.addAll(listOf("-Xlint", "-encoding", "utf8", "-Xdoclint"));
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "com.githonil.snake.Main";
        attributes["Manifest-Version"] = "1.0";
        attributes["Created-By"] = "Githonil";
    }
}